# Generated by Django 5.1.3 on 2024-12-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='user_location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.AddField(
            model_name='clients',
            name='country',
            field=models.CharField(default='nigeria', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clients',
            name='state',
            field=models.CharField(default='lagos', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
