# Generated by Django 5.1.3 on 2024-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clients_gender_clients_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=50, null=True),
        ),
    ]
